    const universities=[];
    const countryMeta=[
      {value:"Netherlands",label:"Нидерланды",flag:"🇳🇱",terms:["нидерланд","голланд","netherlands"]},{value:"Germany",label:"Германия",flag:"🇩🇪",terms:["герман","немец","germany"]},{value:"Finland",label:"Финляндия",flag:"🇫🇮",terms:["финлянд","finland"]},{value:"Estonia",label:"Эстония",flag:"🇪🇪",terms:["эстон","estonia"]},{value:"Hungary",label:"Венгрия",flag:"🇭🇺",terms:["венгр","hungary"]},{value:"Canada",label:"Канада",flag:"🇨🇦",terms:["канад","canada"]},{value:"USA",label:"США",flag:"🇺🇸",terms:["сша","соединенн","америк","usa","united states"]},{value:"UK",label:"Великобритания",flag:"🇬🇧",terms:["великобрит","англи","британ","united kingdom","britain"]},{value:"Spain",label:"Испания",flag:"🇪🇸",terms:["испан","spain"]},{value:"France",label:"Франция",flag:"🇫🇷",terms:["франц","france"]},{value:"Italy",label:"Италия",flag:"🇮🇹",terms:["итал","italy"]},{value:"Poland",label:"Польша",flag:"🇵🇱",terms:["польш","poland"]},{value:"Austria",label:"Австрия",flag:"🇦🇹",terms:["австри","austria"]},{value:"Czechia",label:"Чехия",flag:"🇨🇿",terms:["чех","czech"]},{value:"Sweden",label:"Швеция",flag:"🇸🇪",terms:["швец","sweden"]},{value:"Norway",label:"Норвегия",flag:"🇳🇴",terms:["норвег","norway"]},{value:"UAE",label:"ОАЭ",flag:"🇦🇪",terms:["оаэ","эмират","uae"]},{value:"South Korea",label:"Южная Корея",flag:"🇰🇷",terms:["южн коре","коре","south korea"]},{value:"Japan",label:"Япония",flag:"🇯🇵",terms:["япон","japan"]},
      {value:"Australia",label:"Австралия",flag:"🇦🇺",terms:["австрали","australia"]},{value:"New Zealand",label:"Новая Зеландия",flag:"🇳🇿",terms:["новая зеланд","new zealand"]},{value:"Switzerland",label:"Швейцария",flag:"🇨🇭",terms:["швейцар","switzerland"]},{value:"Belgium",label:"Бельгия",flag:"🇧🇪",terms:["бельги","belgium"]},{value:"Denmark",label:"Дания",flag:"🇩🇰",terms:["дани","denmark"]},{value:"Ireland",label:"Ирландия",flag:"🇮🇪",terms:["ирланд","ireland"]},{value:"Portugal",label:"Португалия",flag:"🇵🇹",terms:["португал","portugal"]},{value:"Greece",label:"Греция",flag:"🇬🇷",terms:["грец","greece"]},{value:"Turkey",label:"Турция",flag:"🇹🇷",terms:["турц","turkey","türkiye"]},{value:"Singapore",label:"Сингапур",flag:"🇸🇬",terms:["сингапур","singapore"]},{value:"China",label:"Китай",flag:"🇨🇳",terms:["кита","china"]},{value:"Malaysia",label:"Малайзия",flag:"🇲🇾",terms:["малайзи","malaysia"]},{value:"Hong Kong",label:"Гонконг",flag:"🇭🇰",terms:["гонконг","hong kong"]},{value:"Qatar",label:"Катар",flag:"🇶🇦",terms:["катар","qatar"]},{value:"Saudi Arabia",label:"Саудовская Аравия",flag:"🇸🇦",terms:["саудов","saudi arabia"]},{value:"Kazakhstan",label:"Казахстан",flag:"🇰🇿",terms:["казахстан","kazakhstan"]},{value:"Lithuania",label:"Литва",flag:"🇱🇹",terms:["литв","lithuania"]},{value:"Latvia",label:"Латвия",flag:"🇱🇻",terms:["латви","latvia"]},{value:"Romania",label:"Румыния",flag:"🇷🇴",terms:["румын","romania"]},{value:"Bulgaria",label:"Болгария",flag:"🇧🇬",terms:["болгар","bulgaria"]},{value:"Cyprus",label:"Кипр",flag:"🇨🇾",terms:["кипр","cyprus"]}
    ];
    const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
    const themeToggle=$("#themeToggle");const isDarkTheme=()=>(document.documentElement.getAttribute("data-theme")||(matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"))==="dark";themeToggle.setAttribute("aria-pressed",String(isDarkTheme()));themeToggle.addEventListener("click",()=>{const next=isDarkTheme()?"light":"dark";document.documentElement.setAttribute("data-theme",next);try{localStorage.setItem("orbit-theme",next)}catch(e){}themeToggle.setAttribute("aria-pressed",String(next==="dark"))});
    const state={generated:false,aiRequest:0,done:JSON.parse(localStorage.getItem("orbit-done")||"[]"),shortlist:JSON.parse(localStorage.getItem("orbit-shortlist")||"[]")};
    const money=n=>"$"+Number(n).toLocaleString("ru-RU");
    const countryInfo=value=>countryMeta.find(x=>x.value===value)||{label:value,flag:"🌍"};
    function parseGoalText(text){
      const lower=(text||"").toLowerCase();
      let countries=countryMeta.filter(c=>c.terms.some(term=>lower.includes(term))).map(c=>c.value);
      if(!countries.length&&/(европ|europe)/.test(lower))countries=["Netherlands","Germany","Finland","Estonia","Hungary","UK"];
      if(!countries.length&&/(северн.{0,8}амер|north america)/.test(lower))countries=["Canada","USA"];
      let interest=null;
      if(/computer science|программ|айти|\bit\b|искусственн.{0,5}интеллект|\bai\b|data science/.test(lower))interest="Computer Science";
      else if(/инженер|engineering|робот/.test(lower))interest="Engineering";
      else if(/бизнес|эконом|финанс|business/.test(lower))interest="Business";
      else if(/дизайн|медиа|design/.test(lower))interest="Design";
      else if(/биолог|медицин|биотех|life science/.test(lower))interest="Life Sciences";
      const decimal=s=>Number(String(s).replace(",","."));
      const digits=s=>Number(String(s).replace(/[^\d]/g,""));
      const budgetMatch=lower.match(/\$\s*([\d\s]{4,7})/)||lower.match(/([\d\s]{4,7})\s*(?:usd|доллар)/);
      const ieltsMatch=lower.match(/ielts\s*[:=]?\s*(\d(?:[.,]\d)?)/);
      const satMatch=lower.match(/sat\s*[:=]?\s*(\d{3,4})/);
      const satMissing=/sat.{0,12}(?:нет|не сдавал|пока без)/.test(lower);
      const gpaMatch=lower.match(/gpa\s*[:=]?\s*(\d(?:[.,]\d)?)/);
      const intakeMatch=lower.match(/20(?:27|28|29)/);
      const locationMatch=lower.match(/(?:^|\s)(?:в|во)\s+([а-яёa-z][а-яёa-z\s-]{2,45}?)(?=\s+(?:на|по|с|бюджет|ielts|sat|gpa|поступление)|[,.]|$)/i);
      return{countries:[...new Set(countries)],locationText:locationMatch?locationMatch[1].trim():"",interest,budget:budgetMatch?digits(budgetMatch[1]):null,ielts:ieltsMatch?decimal(ieltsMatch[1]):null,sat:satMatch?digits(satMatch[1]):satMissing?0:null,gpa:gpaMatch?decimal(gpaMatch[1]):null,intake:intakeMatch?intakeMatch[0]:null};
    }
    function renderUnderstood(parsed){
      const raw=$("#goalText").value.trim();$("#understoodText").textContent=raw?`«${raw}»`:"Начните вводить цель — ORBIT покажет её здесь без сокращений.";
      const geo=parsed.countries.length?parsed.countries.map(c=>`${countryInfo(c).flag} ${countryInfo(c).label}`):[parsed.locationText?`📍 ${parsed.locationText}`:"🌍 География пока не распознана"];
      const items=[...geo,`🎓 ${parsed.interest||$("#interest").value}`,`💰 ${money(parsed.budget||+$("#budget").value)}`,parsed.ielts!==null?`IELTS ${parsed.ielts}`:"IELTS не указан",parsed.intake||$("#intake").value];
      $("#understoodChips").innerHTML=items.map(x=>`<span class="understood-chip">${x}</span>`).join("");
    }
    function applyParsedGoal(){
      const parsed=parseGoalText($("#goalText").value);
      if(parsed.interest)$("#interest").value=parsed.interest;
      if(parsed.budget>=5000&&parsed.budget<=50000)$("#budget").value=parsed.budget;
      if(parsed.ielts!==null)$("#ielts").value=parsed.ielts;
      if(parsed.sat!==null)$("#sat").value=parsed.sat;
      if(parsed.gpa!==null)$("#gpa").value=parsed.gpa;
      if(parsed.intake)$("#intake").value=parsed.intake;
      renderUnderstood(parsed);liveUpdate();
    }
    function getProfile(){const parsed=parseGoalText($("#goalText").value);return{goalText:$("#goalText").value.trim(),countries:parsed.countries,interest:$("#interest").value,gpa:+$("#gpa").value||0,ielts:+$("#ielts").value||0,sat:+$("#sat").value||0,budget:+$("#budget").value,intake:$("#intake").value}}
    function score(u,p){let s=0,reasons=[],risks=[];if(!p.countries.length){s+=15;reasons.push("география поиска открыта")}else if(p.countries.includes(u.country)){s+=30;reasons.push("страна указана в запросе")}else risks.push("это альтернатива за пределами выбранной географии");if(u.fields.includes(p.interest)){s+=28;reasons.push("есть нужное направление")}else risks.push("направление нужно уточнить");if(u.tuition<=p.budget){s+=24;reasons.push("ориентир укладывается в бюджет")}else if(u.tuition<=p.budget*1.25){s+=10;risks.push("понадобится стипендия или больший бюджет")}else risks.push("стоимость выше вашего ориентира");if(!u.ielts||p.ielts>=u.ielts){s+=12;reasons.push(u.ielts?"IELTS выглядит достаточным":"языковой тест нужно сверить")}else risks.push(`поднять IELTS примерно до ${u.ielts}`);if(!u.sat||p.sat>=u.sat){s+=6;reasons.push(u.sat?"SAT проходит демо-порог":"SAT не отмечен обязательным")}else risks.push("усилить SAT или проверить test-optional");return{...u,score:s,reasons,risks}}
    function recommendUniversities(p){return universities.map(u=>score(u,p)).sort((a,b)=>b.score-a.score).slice(0,3)}
    function routeType(u,p){const exams=(!u.ielts||p.ielts>=u.ielts)&&(!u.sat||p.sat>=u.sat),comfortable=u.tuition<=p.budget*.78;if(u.score>=82&&exams&&comfortable)return"резервный";if(u.score>=70&&exams)return"target";return"ambitious"}
    function renderShortlist(p){const saved=state.shortlist.map(name=>universities.find(u=>u.name===name)).filter(Boolean).map(u=>score(u,p));$("#shortlistCount").textContent=`${saved.length} ${saved.length===1?"сохранён":saved.length<5?"сохранено":"сохранено"}`;$("#shortlistGrid").innerHTML=saved.length?saved.map(u=>`<article class="shortlist-item"><span class="route-type">${routeType(u,p)}</span><h3>${u.flag} ${u.name}</h3><div class="shortlist-meta">${u.program} · ${u.fee} · ${u.score}/100</div><button class="remove-shortlist" type="button" data-remove-shortlist="${encodeURIComponent(u.name)}">Удалить из shortlist</button></article>`).join(""):`<div class="empty-shortlist"><b>Shortlist пока пуст.</b> Добавьте понравившийся вариант из рекомендаций — выбор сохранится на этом устройстве.</div>`;$$('[data-remove-shortlist]').forEach(btn=>btn.addEventListener('click',()=>toggleShortlist(decodeURIComponent(btn.dataset.removeShortlist))))}
    function toggleShortlist(name){state.shortlist=state.shortlist.includes(name)?state.shortlist.filter(x=>x!==name):[...state.shortlist,name];localStorage.setItem("orbit-shortlist",JSON.stringify(state.shortlist));renderResults(getProfile());showToast(state.shortlist.includes(name)?"Добавлено в shortlist":"Удалено из shortlist")}
    function liveUpdate(){const p=getProfile(),parsed=parseGoalText(p.goalText),rec=recommendUniversities(p),top=rec[0],geo=p.countries.map(c=>countryInfo(c).label).join(" · ");renderUnderstood(parsed);$("#budgetOut").value=money(p.budget);$("#metricGoal").textContent=`${p.interest} · ${p.intake}`;$("#metricStrength").textContent=p.gpa>=4.3?`GPA ${p.gpa}`:p.ielts>=6.5?`IELTS ${p.ielts}`:"Ясная образовательная цель";$("#metricRisk").textContent=p.ielts<6?"Подготовка к IELTS":top.tuition>p.budget?"Бюджет / стипендия":"Проверить дедлайны";$("#previewUni").textContent=top.name;$("#previewWhy").textContent=top.reasons.slice(0,2).join(" · ")||"Подходит как вариант для дополнительной проверки.";$("#previewTitle").textContent=p.countries.length?`Запрос понят: ${geo}`:parsed.locationText?`Ищем направление: ${parsed.locationText}`:"Нужна страна или регион";$("#previewText").textContent=`В фокусе ${p.interest}; бюджет ${money(p.budget)} в год. В каталоге ${universities.length} программ.`;localStorage.setItem("orbit-profile",JSON.stringify(p));if(state.generated){renderResults(p);showToast("Маршрут обновлён под новый запрос")}}
    function renderResults(p){const rec=recommendUniversities(p),missing=p.countries.filter(c=>!universities.some(u=>u.country===c));$("#strengths").innerHTML=[`GPA ${p.gpa}`,p.ielts?`IELTS ${p.ielts}`:"IELTS ещё не сдан",p.sat?`SAT ${p.sat}`:"SAT ещё не сдан",`Бюджет ${money(p.budget)}`,...missing.map(c=>`В базе пока нет: ${countryInfo(c).label}`)].map((x,i)=>`<span class="token ${((i===1&&!p.ielts)||(i===2&&!p.sat)||i>3)?'warn':''}">${x}</span>`).join("");$("#goalSummary").textContent=`Поступление на ${p.interest} в ${p.intake} году. Приоритет: ${p.countries.length?p.countries.map(c=>countryInfo(c).label).join(", "):"открытый список стран"}; ориентир по бюджету — ${money(p.budget)} в год.${missing.length?" Для стран без проверенных программ показаны ближайшие альтернативы.":""}`;
      $("#uniGrid").innerHTML=rec.map((u,i)=>`<article class="card uni-card"><div class="uni-top"><span class="flag">${u.flag}</span><span class="fit ${u.score<70?'mid':''}">${routeType(u,p)} · ${u.score}/100</span></div><h3>${i+1}. ${u.name}</h3><div class="program">${u.program}</div><div class="scoreline" role="progressbar" aria-label="Совпадение профиля с ${u.name}" aria-valuenow="${u.score}" aria-valuemin="0" aria-valuemax="100"><span style="width:${u.score}%"></span></div><div class="score-caption"><span>совпадение профиля</span><b>${u.score}%</b></div><div class="facts"><span class="fact">${u.city}</span><span class="fact">${u.fee}</span><span class="fact">IELTS ${u.ielts?`≈ ${u.ielts}`:"сверить"}</span></div><p class="why"><b>Почему подходит:</b> ${u.reasons.slice(0,3).join(", ")||"вариант расширяет shortlist"}.</p><p class="watch"><b>Проверить:</b> ${u.risks[0]||"актуальные требования и срок подачи"}.</p><div class="uni-actions"><a class="source" href="${u.url}" target="_blank" rel="noreferrer">Официальный источник ↗</a><button class="save-uni ${state.shortlist.includes(u.name)?'saved':''}" type="button" aria-pressed="${state.shortlist.includes(u.name)}" data-shortlist="${encodeURIComponent(u.name)}">${state.shortlist.includes(u.name)?'✓ Сохранено':'+ Shortlist'}</button></div></article>`).join("");$$('[data-shortlist]').forEach(btn=>btn.addEventListener('click',()=>toggleShortlist(decodeURIComponent(btn.dataset.shortlist))));renderShortlist(p);
      const selected=state.shortlist.map(name=>universities.find(u=>u.name===name)).filter(Boolean).slice(0,2).map(u=>score(u,p)),a=selected[0]||rec[0],b=selected[1]||rec.find(u=>u.name!==a.name)||rec[1];$("#compareMode").textContent=selected.length===2?"ваш shortlist":"лидеры подбора";$("#compareTable").innerHTML=`<table><thead><tr><th>Параметр</th><th>${a.name}</th><th>${b.name}</th></tr></thead><tbody><tr><td>Категория</td><td><b>${routeType(a,p)}</b></td><td><b>${routeType(b,p)}</b></td></tr><tr><td>Совпадение</td><td>${a.score}/100</td><td>${b.score}/100</td></tr><tr><td>Локация</td><td><b>${a.city}, ${countryInfo(a.country).label}</b></td><td><b>${b.city}, ${countryInfo(b.country).label}</b></td></tr><tr><td>Ориентир стоимости</td><td>${a.fee}</td><td>${b.fee}</td></tr><tr><td>IELTS-ориентир</td><td>${a.ielts||"сверить"}</td><td>${b.ielts||"сверить"}</td></tr><tr><td>Главная сила</td><td>${a.strength}</td><td>${b.strength}</td></tr><tr><td>Ваш риск</td><td>${a.risks[0]||"сверить документы"}</td><td>${b.risks[0]||"сверить документы"}</td></tr></tbody></table>`;
      const firstChoice=state.shortlist[0]||a.name,tasks=[{time:"Сейчас",title:state.shortlist.length?`Проверить ${firstChoice}`:"Добавить первый вуз в shortlist",text:state.shortlist.length?"Откройте официальный источник и выпишите требования к документам.":"Сохраните подходящий вариант из рекомендаций, чтобы начать сравнение."},{time:"Следующие 30 дней",title:p.ielts<6.5?"Составить план IELTS":"Собрать shortlist из 5 вузов",text:p.ielts<6.5?"Назначьте дату пробного теста и цель по каждому разделу.":"Сбалансируйте ambitious, target и резервные варианты без гарантий поступления."},{time:"После shortlist",title:"Подготовить документы",text:"Транскрипт, переводы, паспорт, CV и список достижений."},{time:`До набора ${p.intake}`,title:"Сверить дедлайны",text:"Добавьте официальные даты в календарь и проверьте их дважды."}];$("#timeline").innerHTML=tasks.map((t,i)=>`<article class="task ${i===0?'task-now':''}"><div class="task-time">${t.time}</div><h3>${t.title}</h3><p>${t.text}</p><label class="check"><input type="checkbox" data-task="${i}" ${state.done.includes(i)?'checked':''}> Готово</label></article>`).join("");$("#nextAction").textContent=state.done.includes(0)?(state.done.includes(1)?"Соберите документы и создайте календарь дедлайнов":tasks[1].title):tasks[0].title;updateProgress();$$('[data-task]').forEach(x=>x.addEventListener('change',toggleTask));$$('.step').forEach((s,i)=>s.classList.toggle('active',i===4))}
    liveUpdate=function(){const p=getProfile(),parsed=parseGoalText(p.goalText),destination=parsed.countries.length?parsed.countries.map(c=>countryInfo(c).label).join(" · "):parsed.locationText||"любая указанная страна";renderUnderstood(parsed);$("#budgetOut").value=money(p.budget);$("#metricGoal").textContent=`${p.interest} · ${p.intake}`;$("#metricStrength").textContent=p.gpa>=4.3?`GPA ${p.gpa}`:p.ielts>=6.5?`IELTS ${p.ielts}`:"Ясная образовательная цель";$("#metricRisk").textContent=p.ielts<6?"Подготовка к IELTS":"Проверить официальные требования";$("#previewUni").textContent=`AI-поиск: ${destination}`;$("#previewWhy").textContent="После запуска ORBIT найдёт варианты в интернете — статического списка университетов здесь нет.";$("#previewTitle").textContent=`Запрос понят: ${destination}`;$("#previewText").textContent=`В фокусе ${p.interest}; бюджет ${money(p.budget)} в год. Страна берётся прямо из вашего текста.`;localStorage.setItem("orbit-profile",JSON.stringify(p));if(state.generated){renderResults(p);showToast("Профиль обновлён — запустите AI-поиск снова")}};
    renderResults=function(p){const parsed=parseGoalText(p.goalText),destination=parsed.countries.length?parsed.countries.map(c=>countryInfo(c).label).join(", "):parsed.locationText||"страна из вашего запроса";$("#strengths").innerHTML=[`GPA ${p.gpa}`,p.ielts?`IELTS ${p.ielts}`:"IELTS ещё не сдан",p.sat?`SAT ${p.sat}`:"SAT ещё не сдан",`Бюджет ${money(p.budget)}`,`AI ищет: ${destination}`].map((x,i)=>`<span class="token ${((i===1&&!p.ielts)||(i===2&&!p.sat))?'warn':''}">${x}</span>`).join("");$("#goalSummary").textContent=`Поступление на ${p.interest} в ${p.intake} году. География: ${destination}; бюджет — ${money(p.budget)} в год. Университеты будут найдены AI в интернете, а не взяты из встроенного каталога.`;const tasks=[{time:"Сейчас",title:"Изучить найденные источники",text:"Откройте официальные страницы из AI-ответа и отметьте подходящие программы."},{time:"Следующие 30 дней",title:p.ielts<6.5?"Составить план IELTS":"Собрать shortlist из 5 вузов",text:p.ielts<6.5?"Назначьте дату пробного теста и цель по каждому разделу.":"Сравните требования, стоимость и дедлайны только по официальным страницам."},{time:"После shortlist",title:"Подготовить документы",text:"Транскрипт, переводы, паспорт, CV и список достижений."},{time:`До набора ${p.intake}`,title:"Сверить дедлайны",text:"Добавьте официальные даты в календарь и проверьте их перед подачей."}];$("#timeline").innerHTML=tasks.map((t,i)=>`<article class="task ${i===0?'task-now':''}"><div class="task-time">${t.time}</div><h3>${t.title}</h3><p>${t.text}</p><label class="check"><input type="checkbox" data-task="${i}" ${state.done.includes(i)?'checked':''}> Готово</label></article>`).join("");$("#nextAction").textContent=state.done.includes(0)?tasks[1].title:tasks[0].title;updateProgress();$$('[data-task]').forEach(x=>x.addEventListener('change',toggleTask));$$('.step').forEach((s,i)=>s.classList.toggle('active',i===4))};
    function toggleTask(e){const i=+e.target.dataset.task;if(e.target.checked&&!state.done.includes(i))state.done.push(i);if(!e.target.checked)state.done=state.done.filter(x=>x!==i);localStorage.setItem("orbit-done",JSON.stringify(state.done));renderResults(getProfile())}
    function updateProgress(){$("#progressText").textContent=`${state.done.length} из 4 готово`}
    function showToast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove("show"),2200)}
    function criteriaFor(p){return[
      {name:"Академика",value:`GPA ${p.gpa}/5`,good:p.gpa>=4.2,note:p.gpa>=4.2?"сильная база":"усилить оценками и достижениями"},
      {name:"Английский",value:p.ielts?`IELTS ${p.ielts}`:"не сдан",good:p.ielts>=6.5,note:p.ielts>=6.5?"часто проходит порог":"проверить порог программы"},
      {name:"SAT",value:p.sat?String(p.sat):"не сдан",good:p.sat>=1250,note:p.sat>=1250?"конкурентный ориентир":"зависит от страны и вуза"},
      {name:"Бюджет",value:money(p.budget),good:p.budget>=15000,note:"обучение в год"},
      {name:"Срок",value:p.intake,good:true,note:"год поступления"}
    ]}
    function renderCriteria(p){$("#criteriaGrid").innerHTML=criteriaFor(p).map(x=>`<div class="criterion ${x.good?'good':'warn'}"><small>${x.name}</small><b>${x.value}</b><small>${x.note}</small></div>`).join("")}
    function safeHost(url){try{return new URL(url).hostname.replace(/^www\./,"")}catch{return"источник"}}
    function renderAiPlan(data,p){renderCriteria(p);const live=Boolean(data&&data.mode==="live"&&data.answer&&data.sources?.length);$("#aiBadge").className=`ai-badge ${live?'':'fallback'}`;$("#aiBadge").textContent=live?"AI + интернет":"резервный режим";$("#aiMeta").textContent=live?`Поиск завершён · ${data.sources.length} источников · ${new Date(data.generatedAt).toLocaleString("ru-RU")}`:"AI-поиск временно недоступен — локальный план продолжает работать.";$("#aiAnswer").textContent=live?data.answer:"AI не получил достаточно надёжных источников. Уточните страну или направление и повторите поиск — локальный маршрут ниже остаётся доступен.";$("#aiSources").innerHTML=live?data.sources.map(s=>`<a class="ai-source" href="${s.url}" target="_blank" rel="noreferrer"><b>${s.title||"Официальный источник"}</b><span>${safeHost(s.url)}${s.publishedDate?` · ${s.publishedDate}`:""}</span></a>`).join(""):""}
    async function fetchAiPlan(p){const requestId=++state.aiRequest,button=$("#submitRoute");button.disabled=true;button.textContent="AI ищет университеты и требования…";renderCriteria(p);$("#aiBadge").className="ai-badge loading";$("#aiBadge").textContent="ищу в интернете…";$("#aiMeta").textContent="Проверяю программы, требования, стоимость и дедлайны по вашему профилю.";$("#aiAnswer").textContent="Поиск обычно занимает несколько секунд. Сначала смотрим официальные страницы университетов и государственных порталов.";$("#aiSources").innerHTML="";try{const response=await fetch("/api/plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"AI временно недоступен");if(requestId===state.aiRequest)renderAiPlan(data,p)}catch(error){if(requestId===state.aiRequest){renderAiPlan({mode:"fallback"},p);showToast(error.message||"Включён резервный подбор")}}finally{if(requestId===state.aiRequest){button.disabled=false;button.textContent="Обновить AI-поиск и план →"}}}
    $("#profileForm").addEventListener("submit",async e=>{e.preventDefault();if(!$("#goalText").value.trim()){showToast("Опишите свою цель хотя бы одним предложением");return}state.generated=true;$("#results").classList.add("show");const profile=getProfile();renderResults(profile);renderCriteria(profile);setTimeout(()=>$("#results").scrollIntoView({behavior:"smooth",block:"start"}),60);await fetchAiPlan(profile)});
    $("#profileForm").addEventListener("input",e=>e.target.id==="goalText"?applyParsedGoal():liveUpdate());$$('[data-example]').forEach(btn=>btn.addEventListener('click',()=>{$("#goalText").value=btn.dataset.example;applyParsedGoal();showToast("Пример разобран — проверьте профиль")}));$("#nextDone").addEventListener("click",()=>{if(!state.done.includes(0))state.done.push(0);localStorage.setItem("orbit-done",JSON.stringify(state.done));renderResults(getProfile());showToast("Шаг отмечен — прогресс сохранён")});
    const saved=JSON.parse(localStorage.getItem("orbit-profile")||"null");if(saved){if(saved.goalText)$("#goalText").value=saved.goalText;["interest","gpa","ielts","sat","budget","intake"].forEach(id=>{if(saved[id]!==undefined)$("#"+id).value=saved[id]})}applyParsedGoal();
    if(document.modelContext?.registerTool){document.modelContext.registerTool({name:"build_admission_route",title:"Построить маршрут поступления",description:"Разбирает свободное описание цели и показывает рекомендации, сравнение и roadmap.",inputSchema:{type:"object",properties:{goalText:{type:"string"},interest:{type:"string"},gpa:{type:"number"},ielts:{type:"number"},sat:{type:"number"},budget:{type:"number"},intake:{type:"string"}},required:["goalText","interest","gpa","ielts","sat","budget","intake"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{$("#goalText").value=input.goalText;["interest","gpa","ielts","sat","budget","intake"].forEach(id=>$("#"+id).value=input[id]);state.generated=true;$("#results").classList.add("show");liveUpdate();return{status:"ready",understood:getProfile(),recommendations:recommendUniversities(getProfile()).map(x=>x.name),nextAction:$("#nextAction").textContent}}}).catch?.(()=>{})}
